// AUTO-GENERATED by scripts/generate-enums.mjs from the backend OpenAPI
// schema (/v3/api-docs). DO NOT EDIT BY HAND — run `npm run generate-enums`
// after changing the backend enums. Names + feature placement are defined in
// the ENUMS registry in that script; the values come from the live schema.

export type ImageSizeOptions = "LG" | "MD" | "SM" | "XL" | "XS";
export const ImageSizeOptions = {
  LG: "LG",
  MD: "MD",
  SM: "SM",
  XL: "XL",
  XS: "XS",
} as const satisfies Record<ImageSizeOptions, ImageSizeOptions>;
