// AUTO-GENERATED by scripts/generate-enums.mjs from the backend OpenAPI
// schema (/v3/api-docs). DO NOT EDIT BY HAND — run `npm run generate-enums`
// after changing the backend enums. Names + feature placement are defined in
// the ENUMS registry in that script; the values come from the live schema.

export type ThemeAppearance = "DARK" | "LIGHT";
export const ThemeAppearance = {
  DARK: "DARK",
  LIGHT: "LIGHT",
} as const satisfies Record<ThemeAppearance, ThemeAppearance>;
