metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
# Dev-only secret — replace in production
rpc_secret = "4c3a8735a5d4e4b2c0f1d6e9a7b2c5d8e3f0a1b4c7d2e5f8a3b6c9d2e5f8a3b6"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"

[admin]
api_bind_addr = "[::]:3903"
