// AUTO-GENERATED by scripts/generate-enums.mjs from the backend OpenAPI
// schema (/v3/api-docs). DO NOT EDIT BY HAND — run `npm run generate-enums`
// after changing the backend enums. Names + feature placement are defined in
// the ENUMS registry in that script; the values come from the live schema.

export type PublishStatus = "ARCHIVED" | "DRAFT" | "PUBLISHED";
export const PublishStatus = {
  ARCHIVED: "ARCHIVED",
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
} as const satisfies Record<PublishStatus, PublishStatus>;

export type DeckVisibility = "ORG" | "PRIVATE" | "PUBLIC" | "UNLISTED";
export const DeckVisibility = {
  ORG: "ORG",
  PRIVATE: "PRIVATE",
  PUBLIC: "PUBLIC",
  UNLISTED: "UNLISTED",
} as const satisfies Record<DeckVisibility, DeckVisibility>;

export type SlideType = "ALLOCATION" | "DRAWING" | "FOLLOW_UP" | "GRID" | "MATCHING" | "MCQ" | "MEDIA" | "NUMBER" | "PLACE_ON_IMAGE" | "Q_AND_A" | "RANKING" | "SCALES" | "TEXT" | "TITLE";
export const SlideType = {
  ALLOCATION: "ALLOCATION",
  DRAWING: "DRAWING",
  FOLLOW_UP: "FOLLOW_UP",
  GRID: "GRID",
  MATCHING: "MATCHING",
  MCQ: "MCQ",
  MEDIA: "MEDIA",
  NUMBER: "NUMBER",
  PLACE_ON_IMAGE: "PLACE_ON_IMAGE",
  Q_AND_A: "Q_AND_A",
  RANKING: "RANKING",
  SCALES: "SCALES",
  TEXT: "TEXT",
  TITLE: "TITLE",
} as const satisfies Record<SlideType, SlideType>;

export const SLIDE_TYPE_LIST = Object.values(SlideType) as SlideType[];

export type Difficulty = "EASY" | "HARD" | "IMPOSSIBLE" | "MEDIUM";
export const Difficulty = {
  EASY: "EASY",
  HARD: "HARD",
  IMPOSSIBLE: "IMPOSSIBLE",
  MEDIUM: "MEDIUM",
} as const satisfies Record<Difficulty, Difficulty>;

export type ScoreMode = "CLOSEST" | "DISTANCE" | "EXACT" | "INSIDE_RADIUS" | "NEAREST" | "PARTIAL" | "RANGE";
export const ScoreMode = {
  CLOSEST: "CLOSEST",
  DISTANCE: "DISTANCE",
  EXACT: "EXACT",
  INSIDE_RADIUS: "INSIDE_RADIUS",
  NEAREST: "NEAREST",
  PARTIAL: "PARTIAL",
  RANGE: "RANGE",
} as const satisfies Record<ScoreMode, ScoreMode>;

export type McqDataVisualization = "BAR_HORIZONTAL" | "BAR_VERTICAL" | "DONUT" | "LINE" | "NONE" | "PARETO" | "PIE";
export const McqDataVisualization = {
  BAR_HORIZONTAL: "BAR_HORIZONTAL",
  BAR_VERTICAL: "BAR_VERTICAL",
  DONUT: "DONUT",
  LINE: "LINE",
  NONE: "NONE",
  PARETO: "PARETO",
  PIE: "PIE",
} as const satisfies Record<McqDataVisualization, McqDataVisualization>;

export type DisplayLocation = "HEADER" | "LOBBY" | "RESULTS" | "SLIDES" | "TITLE";
export const DisplayLocation = {
  HEADER: "HEADER",
  LOBBY: "LOBBY",
  RESULTS: "RESULTS",
  SLIDES: "SLIDES",
  TITLE: "TITLE",
} as const satisfies Record<DisplayLocation, DisplayLocation>;

export type ResultsDisplayMode = "AFTER_FOLLOWUP" | "IMMEDIATE" | "MANUAL" | "NEVER" | "PRESENTATION_END" | "ROUND_END";
export const ResultsDisplayMode = {
  AFTER_FOLLOWUP: "AFTER_FOLLOWUP",
  IMMEDIATE: "IMMEDIATE",
  MANUAL: "MANUAL",
  NEVER: "NEVER",
  PRESENTATION_END: "PRESENTATION_END",
  ROUND_END: "ROUND_END",
} as const satisfies Record<ResultsDisplayMode, ResultsDisplayMode>;

export type FollowUpMode = "BEST_ANSWER_VOTE" | "PREDICT_POPULAR";
export const FollowUpMode = {
  BEST_ANSWER_VOTE: "BEST_ANSWER_VOTE",
  PREDICT_POPULAR: "PREDICT_POPULAR",
} as const satisfies Record<FollowUpMode, FollowUpMode>;

export const FOLLOW_UP_MODE_LIST = Object.values(FollowUpMode) as FollowUpMode[];
