// AUTO-GENERATED by scripts/generate-validation.mjs from the backend OpenAPI
// schema (/v3/api-docs). DO NOT EDIT BY HAND — run `npm run generate-validation`
// after changing the backend's ValidationConstants / DTO constraints.
//
// Validation bounds are authored once in the backend
// (com.cephadex.ambi.common.validation.ValidationConstants), surfaced via Jakarta
// annotations into OpenAPI, and lifted here so the frontend shares one source of
// truth. Request DTOs are split per feature (mirroring openapi-config.cts); DTOs
// used by 2+ features live in sharedValidationConstants.ts. Keys are OpenAPI schema
// names; values are the per-field facets present.

export const deckValidation = {
  "CommentBodyRequest": {
    "body": {
      "maxLength": 4000
    }
  },
  "MoveSlideRequest": {
    "to": {
      "minimum": 0
    }
  },
  "SetTagsRequest": {
    "tags": {
      "maxItems": 50,
      "items": {
        "minLength": 1,
        "maxLength": 50
      }
    }
  },
  "UpdateDeckRequest": {
    "description": {
      "maxLength": 2000
    },
    "label": {
      "maxLength": 200
    },
    "language": {
      "maxLength": 16
    },
    "name": {
      "maxLength": 200
    }
  }
} as const;

export type DeckValidation = typeof deckValidation;
