// AUTO-GENERATED by scripts/generate-enums.mjs from the backend OpenAPI
// schema (/v3/api-docs). DO NOT EDIT BY HAND — run `npm run generate-enums`
// after changing the backend enums. Names + feature placement are defined in
// the ENUMS registry in that script; the values come from the live schema.

export type UserLevel = "ADMIN" | "GUEST" | "PREMIUM_USER" | "SUPER_ADMIN" | "USER";
export const UserLevel = {
  ADMIN: "ADMIN",
  GUEST: "GUEST",
  PREMIUM_USER: "PREMIUM_USER",
  SUPER_ADMIN: "SUPER_ADMIN",
  USER: "USER",
} as const satisfies Record<UserLevel, UserLevel>;

export type MembershipTier = "FREE" | "INDIVIDUAL" | "ORG_BUSINESS" | "ORG_SEAT" | "ORG_TEAM";
export const MembershipTier = {
  FREE: "FREE",
  INDIVIDUAL: "INDIVIDUAL",
  ORG_BUSINESS: "ORG_BUSINESS",
  ORG_SEAT: "ORG_SEAT",
  ORG_TEAM: "ORG_TEAM",
} as const satisfies Record<MembershipTier, MembershipTier>;

export type MembershipStatus = "ACTIVE" | "CANCELED" | "EXPIRED" | "NONE" | "PAST_DUE" | "TRIALING";
export const MembershipStatus = {
  ACTIVE: "ACTIVE",
  CANCELED: "CANCELED",
  EXPIRED: "EXPIRED",
  NONE: "NONE",
  PAST_DUE: "PAST_DUE",
  TRIALING: "TRIALING",
} as const satisfies Record<MembershipStatus, MembershipStatus>;
