/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LandingPageRouteImport } from './routes/landing-page'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as GamesJoinRouteImport } from './routes/games/join'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections/$collectionId'
import { Route as AuthenticatedScheduledRouteImport } from './routes/_authenticated/scheduled'
import { Route as AuthenticatedMyFavoritesRouteImport } from './routes/_authenticated/my-favorites'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions/$sessionId/index'
import { Route as AuthenticatedDecksIndexRouteImport } from './routes/_authenticated/decks/index'
import { Route as DecksDeckIdViewRouteImport } from './routes/decks/$deckId/view'
import { Route as DecksDeckIdPresentRouteImport } from './routes/decks/$deckId/present'
import { Route as DecksDeckIdEditRouteImport } from './routes/decks/$deckId/edit'
import { Route as DecksDeckIdAnalyticsRouteImport } from './routes/decks/$deckId/analytics'
import { Route as AuthenticatedMyDecksCollectionsRouteImport } from './routes/_authenticated/my-decks/collections'
import { Route as AuthenticatedGamesCreateRouteImport } from './routes/_authenticated/games/create'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesJoinRoute = GamesJoinRouteImport.update({
  id: '/games/join',
  path: '/games/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/collections/$collectionId',
  path: '/collections/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScheduledRoute = AuthenticatedScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyFavoritesRoute =
  AuthenticatedMyFavoritesRouteImport.update({
    id: '/my-favorites',
    path: '/my-favorites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/sessions/$sessionId/',
  path: '/sessions/$sessionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDecksIndexRoute = AuthenticatedDecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DecksDeckIdViewRoute = DecksDeckIdViewRouteImport.update({
  id: '/decks/$deckId/view',
  path: '/decks/$deckId/view',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdPresentRoute = DecksDeckIdPresentRouteImport.update({
  id: '/decks/$deckId/present',
  path: '/decks/$deckId/present',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdEditRoute = DecksDeckIdEditRouteImport.update({
  id: '/decks/$deckId/edit',
  path: '/decks/$deckId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdAnalyticsRoute = DecksDeckIdAnalyticsRouteImport.update({
  id: '/decks/$deckId/analytics',
  path: '/decks/$deckId/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyDecksCollectionsRoute =
  AuthenticatedMyDecksCollectionsRouteImport.update({
    id: '/my-decks/collections',
    path: '/my-decks/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGamesCreateRoute =
  AuthenticatedGamesCreateRouteImport.update({
    id: '/games/create',
    path: '/games/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/design-system': typeof DesignSystemRoute
  '/explore': typeof ExploreRoute
  '/landing-page': typeof LandingPageRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/my-favorites': typeof AuthenticatedMyFavoritesRoute
  '/scheduled': typeof AuthenticatedScheduledRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/games/join': typeof GamesJoinRoute
  '/invite/$token': typeof InviteTokenRoute
  '/games/': typeof GamesIndexRoute
  '/games/create': typeof AuthenticatedGamesCreateRoute
  '/my-decks/collections': typeof AuthenticatedMyDecksCollectionsRoute
  '/decks/$deckId/analytics': typeof DecksDeckIdAnalyticsRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/decks/$deckId/present': typeof DecksDeckIdPresentRoute
  '/decks/$deckId/view': typeof DecksDeckIdViewRoute
  '/decks/': typeof AuthenticatedDecksIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/design-system': typeof DesignSystemRoute
  '/explore': typeof ExploreRoute
  '/landing-page': typeof LandingPageRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/my-favorites': typeof AuthenticatedMyFavoritesRoute
  '/scheduled': typeof AuthenticatedScheduledRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/games/join': typeof GamesJoinRoute
  '/invite/$token': typeof InviteTokenRoute
  '/games': typeof GamesIndexRoute
  '/games/create': typeof AuthenticatedGamesCreateRoute
  '/my-decks/collections': typeof AuthenticatedMyDecksCollectionsRoute
  '/decks/$deckId/analytics': typeof DecksDeckIdAnalyticsRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/decks/$deckId/present': typeof DecksDeckIdPresentRoute
  '/decks/$deckId/view': typeof DecksDeckIdViewRoute
  '/decks': typeof AuthenticatedDecksIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/design-system': typeof DesignSystemRoute
  '/explore': typeof ExploreRoute
  '/landing-page': typeof LandingPageRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/my-favorites': typeof AuthenticatedMyFavoritesRoute
  '/_authenticated/scheduled': typeof AuthenticatedScheduledRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/games/join': typeof GamesJoinRoute
  '/invite/$token': typeof InviteTokenRoute
  '/games/': typeof GamesIndexRoute
  '/_authenticated/games/create': typeof AuthenticatedGamesCreateRoute
  '/_authenticated/my-decks/collections': typeof AuthenticatedMyDecksCollectionsRoute
  '/decks/$deckId/analytics': typeof DecksDeckIdAnalyticsRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/decks/$deckId/present': typeof DecksDeckIdPresentRoute
  '/decks/$deckId/view': typeof DecksDeckIdViewRoute
  '/_authenticated/decks/': typeof AuthenticatedDecksIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/design-system'
    | '/explore'
    | '/landing-page'
    | '/pricing'
    | '/register'
    | '/terms-and-conditions'
    | '/account'
    | '/achievements'
    | '/my-favorites'
    | '/scheduled'
    | '/collections/$collectionId'
    | '/games/join'
    | '/invite/$token'
    | '/games/'
    | '/games/create'
    | '/my-decks/collections'
    | '/decks/$deckId/analytics'
    | '/decks/$deckId/edit'
    | '/decks/$deckId/present'
    | '/decks/$deckId/view'
    | '/decks/'
    | '/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/design-system'
    | '/explore'
    | '/landing-page'
    | '/pricing'
    | '/register'
    | '/terms-and-conditions'
    | '/account'
    | '/achievements'
    | '/my-favorites'
    | '/scheduled'
    | '/collections/$collectionId'
    | '/games/join'
    | '/invite/$token'
    | '/games'
    | '/games/create'
    | '/my-decks/collections'
    | '/decks/$deckId/analytics'
    | '/decks/$deckId/edit'
    | '/decks/$deckId/present'
    | '/decks/$deckId/view'
    | '/decks'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/design-system'
    | '/explore'
    | '/landing-page'
    | '/pricing'
    | '/register'
    | '/terms-and-conditions'
    | '/_authenticated/account'
    | '/_authenticated/achievements'
    | '/_authenticated/my-favorites'
    | '/_authenticated/scheduled'
    | '/collections/$collectionId'
    | '/games/join'
    | '/invite/$token'
    | '/games/'
    | '/_authenticated/games/create'
    | '/_authenticated/my-decks/collections'
    | '/decks/$deckId/analytics'
    | '/decks/$deckId/edit'
    | '/decks/$deckId/present'
    | '/decks/$deckId/view'
    | '/_authenticated/decks/'
    | '/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ExploreRoute: typeof ExploreRoute
  LandingPageRoute: typeof LandingPageRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  GamesJoinRoute: typeof GamesJoinRoute
  InviteTokenRoute: typeof InviteTokenRoute
  GamesIndexRoute: typeof GamesIndexRoute
  DecksDeckIdAnalyticsRoute: typeof DecksDeckIdAnalyticsRoute
  DecksDeckIdEditRoute: typeof DecksDeckIdEditRoute
  DecksDeckIdPresentRoute: typeof DecksDeckIdPresentRoute
  DecksDeckIdViewRoute: typeof DecksDeckIdViewRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page': {
      id: '/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/join': {
      id: '/games/join'
      path: '/games/join'
      fullPath: '/games/join'
      preLoaderRoute: typeof GamesJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scheduled': {
      id: '/_authenticated/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof AuthenticatedScheduledRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-favorites': {
      id: '/_authenticated/my-favorites'
      path: '/my-favorites'
      fullPath: '/my-favorites'
      preLoaderRoute: typeof AuthenticatedMyFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/decks/': {
      id: '/_authenticated/decks/'
      path: '/decks'
      fullPath: '/decks/'
      preLoaderRoute: typeof AuthenticatedDecksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/decks/$deckId/view': {
      id: '/decks/$deckId/view'
      path: '/decks/$deckId/view'
      fullPath: '/decks/$deckId/view'
      preLoaderRoute: typeof DecksDeckIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/present': {
      id: '/decks/$deckId/present'
      path: '/decks/$deckId/present'
      fullPath: '/decks/$deckId/present'
      preLoaderRoute: typeof DecksDeckIdPresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/edit': {
      id: '/decks/$deckId/edit'
      path: '/decks/$deckId/edit'
      fullPath: '/decks/$deckId/edit'
      preLoaderRoute: typeof DecksDeckIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/analytics': {
      id: '/decks/$deckId/analytics'
      path: '/decks/$deckId/analytics'
      fullPath: '/decks/$deckId/analytics'
      preLoaderRoute: typeof DecksDeckIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-decks/collections': {
      id: '/_authenticated/my-decks/collections'
      path: '/my-decks/collections'
      fullPath: '/my-decks/collections'
      preLoaderRoute: typeof AuthenticatedMyDecksCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/create': {
      id: '/_authenticated/games/create'
      path: '/games/create'
      fullPath: '/games/create'
      preLoaderRoute: typeof AuthenticatedGamesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedMyFavoritesRoute: typeof AuthenticatedMyFavoritesRoute
  AuthenticatedScheduledRoute: typeof AuthenticatedScheduledRoute
  AuthenticatedGamesCreateRoute: typeof AuthenticatedGamesCreateRoute
  AuthenticatedMyDecksCollectionsRoute: typeof AuthenticatedMyDecksCollectionsRoute
  AuthenticatedDecksIndexRoute: typeof AuthenticatedDecksIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedMyFavoritesRoute: AuthenticatedMyFavoritesRoute,
  AuthenticatedScheduledRoute: AuthenticatedScheduledRoute,
  AuthenticatedGamesCreateRoute: AuthenticatedGamesCreateRoute,
  AuthenticatedMyDecksCollectionsRoute: AuthenticatedMyDecksCollectionsRoute,
  AuthenticatedDecksIndexRoute: AuthenticatedDecksIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  DesignSystemRoute: DesignSystemRoute,
  ExploreRoute: ExploreRoute,
  LandingPageRoute: LandingPageRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  GamesJoinRoute: GamesJoinRoute,
  InviteTokenRoute: InviteTokenRoute,
  GamesIndexRoute: GamesIndexRoute,
  DecksDeckIdAnalyticsRoute: DecksDeckIdAnalyticsRoute,
  DecksDeckIdEditRoute: DecksDeckIdEditRoute,
  DecksDeckIdPresentRoute: DecksDeckIdPresentRoute,
  DecksDeckIdViewRoute: DecksDeckIdViewRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
