/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LandingPageRouteImport } from './routes/landing-page'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyPacksIndexRouteImport } from './routes/my-packs/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as PulseCreateRouteImport } from './routes/pulse/create'
import { Route as MyPacksCreateRouteImport } from './routes/my-packs/create'
import { Route as GamesJoinRouteImport } from './routes/games/join'
import { Route as GamesCreateRouteImport } from './routes/games/create'
import { Route as MyPacksPackIdEditRouteImport } from './routes/my-packs/$packId/edit'
import { Route as GamesRoomCodeResultsRouteImport } from './routes/games/$roomCode/results'
import { Route as GamesRoomCodePlayRouteImport } from './routes/games/$roomCode/play'
import { Route as GamesRoomCodeLobbyRouteImport } from './routes/games/$roomCode/lobby'
import { Route as DecksDeckIdViewRouteImport } from './routes/decks/$deckId/view'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPacksIndexRoute = MyPacksIndexRouteImport.update({
  id: '/my-packs/',
  path: '/my-packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseCreateRoute = PulseCreateRouteImport.update({
  id: '/pulse/create',
  path: '/pulse/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPacksCreateRoute = MyPacksCreateRouteImport.update({
  id: '/my-packs/create',
  path: '/my-packs/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesJoinRoute = GamesJoinRouteImport.update({
  id: '/games/join',
  path: '/games/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCreateRoute = GamesCreateRouteImport.update({
  id: '/games/create',
  path: '/games/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPacksPackIdEditRoute = MyPacksPackIdEditRouteImport.update({
  id: '/my-packs/$packId/edit',
  path: '/my-packs/$packId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoomCodeResultsRoute = GamesRoomCodeResultsRouteImport.update({
  id: '/games/$roomCode/results',
  path: '/games/$roomCode/results',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoomCodePlayRoute = GamesRoomCodePlayRouteImport.update({
  id: '/games/$roomCode/play',
  path: '/games/$roomCode/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoomCodeLobbyRoute = GamesRoomCodeLobbyRouteImport.update({
  id: '/games/$roomCode/lobby',
  path: '/games/$roomCode/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdViewRoute = DecksDeckIdViewRouteImport.update({
  id: '/decks/$deckId/view',
  path: '/decks/$deckId/view',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/design-system': typeof DesignSystemRoute
  '/landing-page': typeof LandingPageRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/my-packs/create': typeof MyPacksCreateRoute
  '/pulse/create': typeof PulseCreateRoute
  '/games/': typeof GamesIndexRoute
  '/my-packs/': typeof MyPacksIndexRoute
  '/decks/$deckId/view': typeof DecksDeckIdViewRoute
  '/games/$roomCode/lobby': typeof GamesRoomCodeLobbyRoute
  '/games/$roomCode/play': typeof GamesRoomCodePlayRoute
  '/games/$roomCode/results': typeof GamesRoomCodeResultsRoute
  '/my-packs/$packId/edit': typeof MyPacksPackIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/design-system': typeof DesignSystemRoute
  '/landing-page': typeof LandingPageRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/my-packs/create': typeof MyPacksCreateRoute
  '/pulse/create': typeof PulseCreateRoute
  '/games': typeof GamesIndexRoute
  '/my-packs': typeof MyPacksIndexRoute
  '/decks/$deckId/view': typeof DecksDeckIdViewRoute
  '/games/$roomCode/lobby': typeof GamesRoomCodeLobbyRoute
  '/games/$roomCode/play': typeof GamesRoomCodePlayRoute
  '/games/$roomCode/results': typeof GamesRoomCodeResultsRoute
  '/my-packs/$packId/edit': typeof MyPacksPackIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/design-system': typeof DesignSystemRoute
  '/landing-page': typeof LandingPageRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/games/create': typeof GamesCreateRoute
  '/games/join': typeof GamesJoinRoute
  '/my-packs/create': typeof MyPacksCreateRoute
  '/pulse/create': typeof PulseCreateRoute
  '/games/': typeof GamesIndexRoute
  '/my-packs/': typeof MyPacksIndexRoute
  '/decks/$deckId/view': typeof DecksDeckIdViewRoute
  '/games/$roomCode/lobby': typeof GamesRoomCodeLobbyRoute
  '/games/$roomCode/play': typeof GamesRoomCodePlayRoute
  '/games/$roomCode/results': typeof GamesRoomCodeResultsRoute
  '/my-packs/$packId/edit': typeof MyPacksPackIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/design-system'
    | '/landing-page'
    | '/pricing'
    | '/register'
    | '/terms-and-conditions'
    | '/games/create'
    | '/games/join'
    | '/my-packs/create'
    | '/pulse/create'
    | '/games/'
    | '/my-packs/'
    | '/decks/$deckId/view'
    | '/games/$roomCode/lobby'
    | '/games/$roomCode/play'
    | '/games/$roomCode/results'
    | '/my-packs/$packId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/design-system'
    | '/landing-page'
    | '/pricing'
    | '/register'
    | '/terms-and-conditions'
    | '/games/create'
    | '/games/join'
    | '/my-packs/create'
    | '/pulse/create'
    | '/games'
    | '/my-packs'
    | '/decks/$deckId/view'
    | '/games/$roomCode/lobby'
    | '/games/$roomCode/play'
    | '/games/$roomCode/results'
    | '/my-packs/$packId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/design-system'
    | '/landing-page'
    | '/pricing'
    | '/register'
    | '/terms-and-conditions'
    | '/games/create'
    | '/games/join'
    | '/my-packs/create'
    | '/pulse/create'
    | '/games/'
    | '/my-packs/'
    | '/decks/$deckId/view'
    | '/games/$roomCode/lobby'
    | '/games/$roomCode/play'
    | '/games/$roomCode/results'
    | '/my-packs/$packId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  DesignSystemRoute: typeof DesignSystemRoute
  LandingPageRoute: typeof LandingPageRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  GamesCreateRoute: typeof GamesCreateRoute
  GamesJoinRoute: typeof GamesJoinRoute
  MyPacksCreateRoute: typeof MyPacksCreateRoute
  PulseCreateRoute: typeof PulseCreateRoute
  GamesIndexRoute: typeof GamesIndexRoute
  MyPacksIndexRoute: typeof MyPacksIndexRoute
  DecksDeckIdViewRoute: typeof DecksDeckIdViewRoute
  GamesRoomCodeLobbyRoute: typeof GamesRoomCodeLobbyRoute
  GamesRoomCodePlayRoute: typeof GamesRoomCodePlayRoute
  GamesRoomCodeResultsRoute: typeof GamesRoomCodeResultsRoute
  MyPacksPackIdEditRoute: typeof MyPacksPackIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page': {
      id: '/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-packs/': {
      id: '/my-packs/'
      path: '/my-packs'
      fullPath: '/my-packs/'
      preLoaderRoute: typeof MyPacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse/create': {
      id: '/pulse/create'
      path: '/pulse/create'
      fullPath: '/pulse/create'
      preLoaderRoute: typeof PulseCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-packs/create': {
      id: '/my-packs/create'
      path: '/my-packs/create'
      fullPath: '/my-packs/create'
      preLoaderRoute: typeof MyPacksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/join': {
      id: '/games/join'
      path: '/games/join'
      fullPath: '/games/join'
      preLoaderRoute: typeof GamesJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/create': {
      id: '/games/create'
      path: '/games/create'
      fullPath: '/games/create'
      preLoaderRoute: typeof GamesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-packs/$packId/edit': {
      id: '/my-packs/$packId/edit'
      path: '/my-packs/$packId/edit'
      fullPath: '/my-packs/$packId/edit'
      preLoaderRoute: typeof MyPacksPackIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$roomCode/results': {
      id: '/games/$roomCode/results'
      path: '/games/$roomCode/results'
      fullPath: '/games/$roomCode/results'
      preLoaderRoute: typeof GamesRoomCodeResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$roomCode/play': {
      id: '/games/$roomCode/play'
      path: '/games/$roomCode/play'
      fullPath: '/games/$roomCode/play'
      preLoaderRoute: typeof GamesRoomCodePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$roomCode/lobby': {
      id: '/games/$roomCode/lobby'
      path: '/games/$roomCode/lobby'
      fullPath: '/games/$roomCode/lobby'
      preLoaderRoute: typeof GamesRoomCodeLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/view': {
      id: '/decks/$deckId/view'
      path: '/decks/$deckId/view'
      fullPath: '/decks/$deckId/view'
      preLoaderRoute: typeof DecksDeckIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  DesignSystemRoute: DesignSystemRoute,
  LandingPageRoute: LandingPageRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  GamesCreateRoute: GamesCreateRoute,
  GamesJoinRoute: GamesJoinRoute,
  MyPacksCreateRoute: MyPacksCreateRoute,
  PulseCreateRoute: PulseCreateRoute,
  GamesIndexRoute: GamesIndexRoute,
  MyPacksIndexRoute: MyPacksIndexRoute,
  DecksDeckIdViewRoute: DecksDeckIdViewRoute,
  GamesRoomCodeLobbyRoute: GamesRoomCodeLobbyRoute,
  GamesRoomCodePlayRoute: GamesRoomCodePlayRoute,
  GamesRoomCodeResultsRoute: GamesRoomCodeResultsRoute,
  MyPacksPackIdEditRoute: MyPacksPackIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
