// AUTO-GENERATED by scripts/generate-validation.mjs from the backend OpenAPI
// schema (/v3/api-docs). DO NOT EDIT BY HAND — run `npm run generate-validation`
// after changing the backend's ValidationConstants / DTO constraints.
//
// Validation bounds are authored once in the backend
// (com.cephadex.ambi.common.validation.ValidationConstants), surfaced via Jakarta
// annotations into OpenAPI, and lifted here so the frontend shares one source of
// truth. Request DTOs are split per feature (mirroring openapi-config.cts); DTOs
// used by 2+ features live in sharedValidationConstants.ts. Keys are OpenAPI schema
// names; values are the per-field facets present.

export const liveSessionValidation = {
  "CreateSessionRequest": {
    "deckId": {
      "minLength": 1
    }
  },
  "HostAnswerRequest": {
    "answer": {
      "maxLength": 1000
    }
  },
  "JoinSessionRequest": {
    "displayName": {
      "maxLength": 60
    },
    "roomCode": {
      "minLength": 1
    }
  },
  "QAndAAnswer": {
    "question": {
      "maxLength": 500
    }
  },
  "SubmitAnswerRequest": {
    "slideId": {
      "minLength": 1
    }
  },
  "SubmitVoteRequest": {
    "optionId": {
      "minLength": 1
    },
    "slideId": {
      "minLength": 1
    }
  },
  "TextAnswer": {
    "text": {
      "maxLength": 500
    }
  }
} as const;

export type LiveSessionValidation = typeof liveSessionValidation;
