// AUTO-GENERATED by scripts/generate-validation.mjs from the backend OpenAPI
// schema (/v3/api-docs). DO NOT EDIT BY HAND — run `npm run generate-validation`
// after changing the backend's ValidationConstants / DTO constraints.
//
// Validation bounds are authored once in the backend
// (com.cephadex.ambi.common.validation.ValidationConstants), surfaced via Jakarta
// annotations into OpenAPI, and lifted here so the frontend shares one source of
// truth. Keys are OpenAPI schema names; values are the per-field facets present.

export const validation = {
  "AddImageRequest": {
    "name": {
      "maxLength": 200
    }
  },
  "AvatarSelection": {
    "externalSrc": {
      "maxLength": 2048
    },
    "internalAvatarId": {
      "maxLength": 64
    }
  },
  "CommentBodyRequest": {
    "body": {
      "maxLength": 4000
    }
  },
  "CreateThemeRequest": {
    "name": {
      "maxLength": 200
    }
  },
  "MoveSlideRequest": {
    "to": {
      "minimum": 0
    }
  },
  "Pageable": {
    "page": {
      "minimum": 0
    },
    "size": {
      "minimum": 1
    }
  },
  "RegisterRequest": {
    "displayName": {
      "maxLength": 60
    },
    "username": {
      "minLength": 3,
      "maxLength": 30,
      "pattern": "[A-Za-z0-9._-]+"
    }
  },
  "RenameGalleryRequest": {
    "name": {
      "maxLength": 200
    }
  },
  "SetTagsRequest": {
    "tags": {
      "maxItems": 50,
      "items": {
        "minLength": 1,
        "maxLength": 50
      }
    }
  },
  "UpdateDeckRequest": {
    "description": {
      "maxLength": 2000
    },
    "language": {
      "maxLength": 16
    },
    "name": {
      "maxLength": 200
    }
  },
  "UpdateProfileRequest": {
    "displayName": {
      "minLength": 1,
      "maxLength": 60
    },
    "timezone": {
      "maxLength": 64
    }
  },
  "UpdateThemeRequest": {
    "name": {
      "maxLength": 200
    }
  }
} as const;

export type Validation = typeof validation;
